openapi: 3.0.0
info:
  title: User API
  version: 1.0.0

tags:
  - name: users
    description: users API
  - name: authentication
    description: auth API

paths:
  /users:
    get:
      tags:
        - users
      summary: Find All Users
      responses:
        200:
          description: OK
        500:
          description: Server Error

    post:
      tags:
        - users
      summary: Add User
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        201:
          description: Created
        400:
          description: Bad Request
        409:
          description: Conflict
        500:
          description: Server Error

  /users/{id}:
    get:
      tags:
        - users
      summary: Find User By Id
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: OK
        409:
          description: Conflict
        500:
          description: Server Error

    put:
      tags:
        - users
      summary: Update User By Id
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        200:
          description: OK
        400:
          description: Bad Request
        409:
          description: Conflict
        500:
          description: Server Error

    delete:
      tags:
        - users
      summary: Delete User By Id
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: OK
        409:
          description: Conflict
        500:
          description: Server Error

  /auth/signup:
    post:
      tags:
        - authentication
      summary: Register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserCredentials'
      responses:
        201:
          description: User registered successfully
        400:
          description: Bad request

  /auth/signin:
    post:
      tags:
        - authentication
      summary: Authenticate an existing user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserCredentials'
      responses:
        200:
          description: Authentication successful
        401:
          description: Unauthorized

components:
  schemas:
    User:
      type: object
      required:
        - email
        - password
      properties:
        email:
          type: string
          description: User Email
        password:
          type: string
          description: User Password

    UserCredentials:
      type: object
      required:
        - email
        - password
      properties:
        email:
          type: string
          format: email
          example: user@example.com
        password:
          type: string
          format: password
          example: strongPassword123
